#! /bin/bash
# Open a current gif of the NWS radar report for North Florida

echo "Loading radar GIF in Windows"

#the brackets and &> /dev/null get rid of the output
{
# get the GIF
wget -O ~/trash/radar.gif "https://radar.weather.gov/lite/N0R/JAX_loop.gif"

#open in windows, through CMD
cmd.exe /C start  C:/Users/kawaiiPlatAdmin/AppData/Local/Packages/CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc/LocalState/rootfs/home/kawaiiplat/trash/radar.gif
} &> /dev/null
echo "Radar Loaded"
